Contacts: PCI RCS Patch Set 7.
 - Occurred "com.android.contacts" force close 9 times at
   java.lang.RuntimeException: Unable to start activity ComponentInfo.
 - It still display "add to blacklist" after added.
 - Occurred "com.android.contacts" 8 times at
   android.content.ActivityNotFoundException: No Activity found to handle
   Intent { act=com.suntek.mway.rcs.nativeui.ui.BACKUP_RESTORE_ACTIVITY }.
 - Occurred "com.android.contacts" 7 times at java.lang.NullPointerException:
   Attempt to invoke virtual method 'boolean android.content.Intent.
   migrateExtraStreamToClipData()' on a null object reference.
 - Occurred "com.android.contacts" 16 times at java.lang.RuntimeException:
   Unable to start activity ComponentInfo{com.android.contacts/com.android.
   contacts.quickcontact.MyQrcodeActivity}.
 - It will exit contact app when adding 2000 contacts to local group.
 - OOM during contact case.
 - Enhance screen in contact doesn't work.

CRs-Fixed: 806743 816199 822745 822746 821509 809499 816966 824039 806724.
(cherry picked from commit 4fbc0112342ef3aa5b65a6be6ce849ef84b08bc6)

Change-Id: I3ae3f6c61bd9371b141bc3f48b8af0252880f0be